/* ---------- 託運單查詢 shipmentInquiry ---------- */
export const GET_SHIPMENT_LIST = 'GET_SHIPMENT_LIST'
export const GET_SHIPMENT_LIST_SUCCESS = 'GET_SHIPMENT_LIST_SUCCESS'
export const GET_SHIPMENT_LIST_FAILURE = 'GET_SHIPMENT_LIST_FAILURE'
export const RESET_SHIPMENT_LIST = 'RESET_SHIPMENT_LIST'

export const GET_INVOICE_SUMMARY = 'GET_INVOICE_SUMMARY'
export const GET_INVOICE_SUMMARY_SUCCESS = 'GET_INVOICE_SUMMARY_SUCCESS'
export const GET_INVOICE_SUMMARY_FAILURE = 'GET_INVOICE_SUMMARY_FAILURE'
export const RESET_INVOICE_SUMMARY = 'RESET_INVOICE_SUMMARY'

export const GET_SHIPMENT_EXCEPTION = 'GET_SHIPMENT_EXCEPTION'
export const GET_SHIPMENT_EXCEPTION_SUCCESS = 'GET_SHIPMENT_EXCEPTION_SUCCESS'
export const GET_SHIPMENT_EXCEPTION_FAILURE = 'GET_SHIPMENT_EXCEPTION_FAILURE'
export const RESET_SHIPMENT_EXCEPTION = 'RESET_SHIPMENT_EXCEPTION'

export const RESET_SHIPMENT_INQUIRY = 'RESET_SHIPMENT_INQUIRY'

/* ---------- 批次託運匯入 batchShipmentImport ---------- */
export const PARSE_SHIPMENT_FILE = 'PARSE_SHIPMENT_FILE'
export const PARSE_SHIPMENT_FILE_SUCCESS = 'PARSE_SHIPMENT_FILE_SUCCESS'
export const PARSE_SHIPMENT_FILE_FAILURE = 'PARSE_SHIPMENT_FILE_FAILURE'

export const UPDATE_STAGING_ROW = 'UPDATE_STAGING_ROW'
export const REMOVE_STAGING_ROW = 'REMOVE_STAGING_ROW'

export const SUBMIT_BATCH_SHIPMENT = 'SUBMIT_BATCH_SHIPMENT'
export const SUBMIT_BATCH_SHIPMENT_SUCCESS = 'SUBMIT_BATCH_SHIPMENT_SUCCESS'
export const SUBMIT_BATCH_SHIPMENT_FAILURE = 'SUBMIT_BATCH_SHIPMENT_FAILURE'

export const RESET_BATCH_SHIPMENT_IMPORT = 'RESET_BATCH_SHIPMENT_IMPORT'
