export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE'

export const GET_SHIPPING_ACCOUNTS = 'GET_SHIPPING_ACCOUNTS'
export const GET_SHIPPING_ACCOUNTS_SUCCESS = 'GET_SHIPPING_ACCOUNTS_SUCCESS'
export const GET_SHIPPING_ACCOUNTS_FAILURE = 'GET_SHIPPING_ACCOUNTS_FAILURE'

export const RESET_LOOKUP = 'RESET_LOOKUP'
